In [41]:
import open3d as o3d
import os

In [42]:
import open3d as o3d
import os
import numpy as np
from open3d import *    

directory = r"C:\Users\Personal\Desktop\SewerMapper\point_clouds"
file = '2020-08-13_09_46_52.973_527_quick'

path = os.path.join(directory, file + "." + 'ply')

pcd = o3d.io.read_point_cloud(path)
print(pcd)

geometry::PointCloud with 121163 points.


In [43]:
print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud(path)
print(pcd)
print(np.asarray(pcd.points))

Load a ply point cloud, print it, and render it
geometry::PointCloud with 121163 points.
[[ 1.18144107  0.03721849 -3.2874217 ]
 [ 1.18162167  0.0330014  -3.26812363]
 [ 1.18086302  0.03036323 -3.24864244]
 ...
 [-1.08118296  0.25833976 -0.1619302 ]
 [-1.08221006  0.26531026 -0.16251419]
 [-1.08208799  0.28020033 -0.16065003]]


In [44]:
o3d.visualization.draw_geometries([pcd])

RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 

In [26]:
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1,0,0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0,1,0)
o3d.visualization.draw_geometries([pcd, aabb, obb])

RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: The handle is invalid. 

In [31]:
import open3d as o3d
import numpy as np
import trimesh
from scipy.spatial import Delaunay

In [32]:
import open3d as o3d
import trimesh
import numpy as np

pcd = o3d.io.read_point_cloud(path)
pcd.estimate_normals()

# estimate radius for rolling ball
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 1.5 * avg_dist   

mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
           pcd,
           o3d.utility.DoubleVector([radius, radius * 2]))

# create the triangular mesh with the vertices and faces from open3d
tri_mesh = trimesh.Trimesh(np.asarray(mesh.vertices), np.asarray(mesh.triangles),
                          vertex_normals=np.asarray(mesh.vertex_normals))

trimesh.convex.is_convex(tri_mesh)

False

In [34]:
mesh

geometry::TriangleMesh with 121163 points and 86959 triangles.

In [37]:
o3d.visualization.draw_geometries([mesh])

RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: The handle is invalid. 

In [45]:
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist

In [46]:
bpa_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd,o3d.utility.DoubleVector([radius, radius * 2]))

RuntimeError: [Open3D ERROR] ReconstructBallPivoting requires normals

In [47]:
dec_mesh = mesh.simplify_quadric_decimation(100000)

In [48]:
dec_mesh

geometry::TriangleMesh with 121163 points and 86959 triangles.

In [51]:
o3d.io.write_triangle_mesh("mesh.ply", dec_mesh)

True