In [1]:
import open3d as o3d
import os

In [2]:
import pyvista

In [8]:
import open3d as o3d
import os
import numpy as np
from open3d import *    

#directory = r"C:\Users\Personal\Desktop\SewerMapper\point_clouds"
#directory = r"C:\Users\Personal\Desktop\SewerMapper\point_clouds"
file = '2020-08-13_09_46_52.973_527_quick'

path = os.path.join('p.ply')

pcd = o3d.io.read_point_cloud('p.ply')
print(pcd)

geometry::PointCloud with 123992 points.


In [9]:
print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud(path)
print(pcd)
print(np.asarray(pcd.points))

Load a ply point cloud, print it, and render it
geometry::PointCloud with 123992 points.
[[ 1.1234771   0.19434224 -3.50044036]
 [ 1.12165296  0.19524662 -3.48920417]
 [ 1.12270606  0.19538581 -3.46923494]
 ...
 [-0.99797887 -0.42594537 -0.14802796]
 [-0.99200094 -0.33530051 -0.14363541]
 [-1.00386798 -0.42634213 -0.14766589]]


In [10]:
o3d.visualization.draw_geometries([pcd])

In [11]:
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1,0,0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0,1,0)
o3d.visualization.draw_geometries([pcd, aabb, obb])

In [22]:
import open3d as o3d
import numpy as np
import trimesh
from scipy.spatial import Delaunay

In [24]:
import open3d as o3d
import trimesh
import numpy as np

pcd = o3d.io.read_point_cloud('p.ply')
pcd.estimate_normals()

# estimate radius for rolling ball
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 1.5 * avg_dist   

mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
           pcd,
           o3d.utility.DoubleVector([radius, radius * 2]))

# create the triangular mesh with the vertices and faces from open3d
tri_mesh = trimesh.Trimesh(np.asarray(mesh.vertices), np.asarray(mesh.triangles),
                          vertex_normals=np.asarray(mesh.vertex_normals))

trimesh.convex.is_convex(tri_mesh)

False

In [14]:
mesh

geometry::TriangleMesh with 123992 points and 109404 triangles.

In [25]:
o3d.visualization.draw_geometries([mesh])

In [16]:
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist

In [26]:
bpa_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd,o3d.utility.DoubleVector([radius, radius * 2]))

In [27]:
dec_mesh = mesh.simplify_quadric_decimation(100000)

In [28]:
dec_mesh

geometry::TriangleMesh with 118848 points and 100000 triangles.

In [29]:
o3d.io.write_triangle_mesh("mesh.ply", dec_mesh)

True